FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npx tsc

FROM node:20-alpine AS release

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --production

COPY --from=builder app/dist ./dist

CMD ["node", "dist/index.js"]
